# This file may be used to create an environment using:
# $ conda env create -f environment.yml
# platform: linux-64
name: HAMLET
channels:
  - bioconda
  - conda-forge
dependencies:
  - bs4=4.11
  - peppy>=0.35
  - pytest-workflow>=1.6.0
  - snakemake-minimal=7.32
  - snakefmt=0.10.0
  - black=24.3.0
  - sphinx=7.1.2
  - sphinx-rtd-theme
 
