# This file may be used to create an environment using:
# $ conda env create -f environment.yml
# platform: linux-64
name: HAMLET
channels:
  - bioconda
  - conda-forge
dependencies:
  - bs4=4.12
  - peppy=0.40.7
  - pytest-workflow=2.1.0
  - snakemake-minimal=8.24.1
  - snakefmt=0.10.2
  - sphinx=8.1.3
  - sphinx-rtd-theme=3.0.0
