# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
name: HAMLET
dependencies:
 - _libgcc_mutex=0.1=conda_forge
 - _openmp_mutex=4.5=0_gnu
 - pytest-workflow
 - python=3.6
 - snakemake=5.9
