channels:
- bioconda
- r
- conda-forge
- defaults
dependencies:
- pytest-workflow
- snakemake
- drmaa
- pip:
  - "git+https://github.com/bow/rattle.git@69f64e4e86559fcd48a40a2019f2997912147218#egg=Rattle"
