# This file may be used to create an environment using:
# $ conda env create -f environment.yml
# platform: linux-64
name: HAMLET
channels:
  - bioconda
  - conda-forge
dependencies:
 - pytest-workflow>=1.4.0
 - python>3.6
 - snakemake-minimal=5.9
